import Head from "next/head";
import {
  CardListContainer,
  OuterSearchBarContainer,
  SearchBarContainer,
  TitleContainer,
} from "@/pages/index.styles";
import GameDisplayCard from "@/components/GameDisplayCard/GameDisplayCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Hahmlet"
          rel="stylesheet"
        />
      </Head>
      <div>
        <TitleContainer>Backlog estimator</TitleContainer>

        <OuterSearchBarContainer>
          <SearchBarContainer
            placeholder="Search for a game...."
            cols="57"
            rows="1"
          />
        </OuterSearchBarContainer>

        <CardListContainer>
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
        </CardListContainer>
      </div>
    </>
  );
}
