import Head from "next/head";
import {
  CardListContainer,
  OuterSearchBarContainer,
  SearchBarContainer,
  TitleContainer,
} from "@/pages/index.styles";
import GameDisplayCard from "@/components/GameDisplayCard/GameDisplayCard";
import { useEffect, useState } from "react";

export default function Home() {
  const [gameQuery, setGameQuery] = useState();
  const [timeoutId, setTimeoutId] = useState();

  async function getGameResults() {
    const hltbFetch = await fetch(`/api/hltb?q=${gameQuery}`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    });
    const hltbJson = await hltbFetch.json();
    console.log(hltbJson);
  }

  const handleSearchBar = (newQuery) => {
    setGameQuery(newQuery);
    if (timeoutId) {
      clearTimeout(timeoutId);
    }
    const changeQuery = setTimeout(() => {
      getGameResults();
    }, 2000);
    setTimeoutId(changeQuery);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Hahmlet"
          rel="stylesheet"
        />
      </Head>
      <div>
        <TitleContainer>Backlog estimator</TitleContainer>

        <OuterSearchBarContainer>
          <SearchBarContainer
            placeholder="Search for a game...."
            cols="57"
            rows="1"
            onChange={(e) => handleSearchBar(e.target.value)}
          />
        </OuterSearchBarContainer>

        <CardListContainer>
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
        </CardListContainer>
      </div>
    </>
  );
}
