import Head from "next/head";
import {
  CardListContainer,
  OuterSearchBarContainer,
  SearchBarContainer,
  TitleContainer,
} from "@/pages/index.styles";
import GameDisplayCard from "@/components/GameDisplayCard/GameDisplayCard";



const dummy = "Nioh";
async function getGameResults(gameTitle) {
  const hltbFetch = await fetch(`/api/hltb?q=${gameTitle}`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });
  const hltbJson = await hltbFetch.json();
  console.log(hltbJson);
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Hahmlet"
          rel="stylesheet"
        />
      </Head>
      <div>
        <TitleContainer>Backlog estimator</TitleContainer>

        <button
          onClick={() => getGameResults(dummy)}
        ></button>

        <OuterSearchBarContainer>
          <SearchBarContainer
            placeholder="Search for a game...."
            cols="57"
            rows="1"
          />
        </OuterSearchBarContainer>

        <CardListContainer>
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
          <GameDisplayCard />
        </CardListContainer>
      </div>
    </>
  );
}
